"""Profile the raw Olist CSVs and generate docs/data_dictionary.md from the ACTUAL files."""
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"

META = {
 "olist_customers_dataset.csv": ("One row per customer_id (a per-order customer key). customer_unique_id identifies the real person.",
   "customer_id", "-", {"customer_id":"Key given to each order; links to orders","customer_unique_id":"Real customer identity; use this to count repeat buyers","customer_zip_code_prefix":"First 5 digits of zip code","customer_city":"Customer city","customer_state":"Customer state (2-letter code)"}),
 "olist_geolocation_dataset.csv": ("Lat/long per zip-code prefix; many rows per prefix (not unique).",
   "none (zip prefix repeats)", "geolocation_zip_code_prefix -> customers/sellers zip prefix (many-to-many)", {"geolocation_zip_code_prefix":"First 5 digits of zip","geolocation_lat":"Latitude","geolocation_lng":"Longitude","geolocation_city":"City","geolocation_state":"State"}),
 "olist_order_items_dataset.csv": ("One row per item in an order.",
   "(order_id, order_item_id)", "order_id -> orders; product_id -> products; seller_id -> sellers", {"order_id":"Order key","order_item_id":"Item sequence number within the order","product_id":"Product key","seller_id":"Seller key","shipping_limit_date":"Seller deadline to hand the item to the carrier","price":"Item price (BRL)","freight_value":"Freight charged for the item (BRL)"}),
 "olist_order_payments_dataset.csv": ("One row per payment; an order can have several payments (e.g. voucher + card).",
   "(order_id, payment_sequential)", "order_id -> orders", {"order_id":"Order key","payment_sequential":"Payment sequence within the order","payment_type":"Payment method","payment_installments":"Number of installments","payment_value":"Amount paid (BRL)"}),
 "olist_order_reviews_dataset.csv": ("Customer satisfaction reviews. review_id is NOT unique and some orders have several reviews.",
   "none clean (review_id repeats); (review_id, order_id) is unique", "order_id -> orders", {"review_id":"Review key (repeats)","order_id":"Order key","review_score":"Score 1-5","review_comment_title":"Optional title (Portuguese)","review_comment_message":"Optional comment (Portuguese)","review_creation_date":"Date the survey was sent","review_answer_timestamp":"Time the review was answered"}),
 "olist_orders_dataset.csv": ("One row per order with status and lifecycle timestamps.",
   "order_id", "customer_id -> customers", {"order_id":"Order key","customer_id":"Customer key (unique per order)","order_status":"Order status","order_purchase_timestamp":"Purchase time","order_approved_at":"Payment approval time","order_delivered_carrier_date":"Handed to carrier","order_delivered_customer_date":"Delivered to customer","order_estimated_delivery_date":"Estimated delivery date shown to customer"}),
 "olist_products_dataset.csv": ("One row per product. Note the source spells 'lenght' (typo kept as-is).",
   "product_id", "product_category_name -> category translation", {"product_id":"Product key","product_category_name":"Category (Portuguese)","product_name_lenght":"Characters in product name","product_description_lenght":"Characters in description","product_photos_qty":"Number of photos","product_weight_g":"Weight in grams","product_length_cm":"Length (cm)","product_height_cm":"Height (cm)","product_width_cm":"Width (cm)"}),
 "olist_sellers_dataset.csv": ("One row per seller.", "seller_id", "-", {"seller_id":"Seller key","seller_zip_code_prefix":"Zip prefix","seller_city":"Seller city","seller_state":"Seller state"}),
 "product_category_name_translation.csv": ("Portuguese -> English category names.", "product_category_name", "-", {"product_category_name":"Category (Portuguese)","product_category_name_english":"Category (English)"}),
}

def kind(name, s):
    if "date" in name or "timestamp" in name or name.endswith("_at"): return "date/time"
    if pd.api.types.is_numeric_dtype(s): return "numeric"
    return "categorical/text"

out = ["# Data Dictionary", "",
 "Generated by `scripts/profile_raw.py` from the actual Olist CSV files (nothing assumed). Currency is BRL.", ""]
summary = ["| File | Rows | Columns | Duplicate rows | Primary key | Foreign keys |", "|---|---:|---:|---:|---|---|"]
details = []
for f, (desc, pk, fk, cols) in META.items():
    df = pd.read_csv(RAW / f)
    dup = int(df.duplicated().sum())
    summary.append(f"| `{f}` | {len(df):,} | {df.shape[1]} | {dup:,} | {pk} | {fk} |")
    d = [f"## `{f}`", "", desc, "", f"Rows: **{len(df):,}** | Columns: **{df.shape[1]}** | Duplicate rows: **{dup:,}**", "",
         "| Column | Type (pandas) | Role | Missing | Distinct | Description |", "|---|---|---|---:|---:|---|"]
    for c in df.columns:
        d.append(f"| `{c}` | {df[c].dtype} | {kind(c, df[c])} | {int(df[c].isna().sum()):,} | {df[c].nunique():,} | {cols.get(c,'')} |")
    details.append("\n".join(d) + "\n")
out += ["## Overview", ""] + summary + [""] + ["## Relationships", "",
 "```",
 "customers 1 --- N orders 1 --- N order_items N --- 1 products N --- 1 category_translation",
 "                    |  \\                        N --- 1 sellers",
 "                    |   \\-- 1 --- N order_payments",
 "                    \\------ 1 --- N order_reviews (mostly 1, sometimes >1)",
 "```", "",
 "- `customer_id` is unique per order; **`customer_unique_id`** is the true customer (used for repeat-purchase analysis).",
 "- Revenue fields: `price` (product value), `freight_value` (shipping charged), `payment_value` (cash actually paid).",
 "- **There is no product cost or profit field** anywhere in the dataset.", ""] + details
(ROOT / "docs" / "data_dictionary.md").write_text("\n".join(out))
print("wrote docs/data_dictionary.md")
